const char* stateStr[] ={
	"measuring the robot positition relatively to the ROBOT STATION banner",
	"searching for the charging station",
	"approaching the charging station",
	"measuring robot position",
	"attempting to dock",
	"adjusting robot position",
	"adjusting undock pose - step 1",
	"adjusting undock pose - step 2",
	"measuring undock pose - step 1",
	"measuring undock pose - step 2",
	"waiting for charger signal",
	"undocking to try again",
	"idle",
	"feeding",
	"hungry",
	"ready to go",
	"afraid that it crashed",
	"confident about the charging station position",
	"calibration procedure not finished correctly",
	"happy to finish a random walk",
	"realizing to be too slow",
	"aborted",
	"angry to be preemted",
	"relucant to perform",
	"rotating to align with station",
	"aligning with station",
	"rotating to face the station",
	"leaving station",
	"preparing for autonomous run",
	"performing a test movement",
	"checking if not on the charger already",
	"preparing to undock",
	"preparing for calibration",
	"turning head off",
	"turning head on",
	"testmove1",
	"testmove2",
	"testmove3",
	"in an unknown state"
};

typedef enum{
	STATE_CALIBRATE=0,
	STATE_SEARCH,
	STATE_APPROACH,
	STATE_MEASURE,
	STATE_DOCK,
	STATE_ADJUST,
	STATE_UNDOCK_ADJUST_STEP1,
	STATE_UNDOCK_ADJUST_STEP2,
	STATE_UNDOCK_MEASURE1,
	STATE_UNDOCK_MEASURE2,
	STATE_WAIT,
	STATE_RETRY,
	STATE_IDLE,
	STATE_DOCKING_SUCCESS,
	STATE_DOCKING_FAILURE,
	STATE_UNDOCKING_SUCCESS,
	STATE_UNDOCKING_FAILURE,
	STATE_CALIBRATION_SUCCESS,
	STATE_CALIBRATION_FAILURE,
	STATE_TEST_SUCCESS,
	STATE_TIMEOUT,
	STATE_ABORTED,
	STATE_PREEMPTED,
	STATE_REJECTED,
	STATE_ROTATE,
	STATE_MOVE_TO,
	STATE_ROTATE_BACK,
	STATE_UNDOCK_MOVE,
	STATE_UNDOCK_ROTATE,
	STATE_TEST_MOVE,
	STATE_INIT,
	STATE_UNDOCK_INIT,
	STATE_CALIBRATE_INIT,
	STATE_HEAD_ON,
	STATE_HEAD_OFF,
	STATE_TEST1,
	STATE_TEST2,
	STATE_TEST3,
	STATE_NUMBER
}EState;


