#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Logitec F710 wireless gamepad as /dev/input/rumblepad."
echo ""

sudo cp `rospack find scitos_teleop`/udev/73-scitos-teleop-persistent-joystick.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
